# Generated by Django 5.0.6 on 2024-07-16 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_debit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Debit',
        ),
    ]
