# Generated by Django 5.0.6 on 2024-07-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_departement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='departement',
        ),
    ]
