# Generated by Django 5.0.6 on 2024-07-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_debit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='note',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
