# Generated by Django 5.0.6 on 2024-07-26 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customuser_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='departement',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departement2', to='account.departement'),
        ),
    ]
