# Generated by Django 5.0.6 on 2024-07-24 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='poste',
        ),
    ]
